### ISSUE TITLE
Watch directory recursively

### ISSUE THREAD

**Issue by NV** [TwP/directory_watcher#1]
Feature request.

```
dw = DirectoryWatcher.new '/tmp', :scanner => :em
dw.add_observer {
  |*args| args.each {|event| puts event}
}
dw.start

$ echo 'buz' > /tmp/buz
$ mkdir /tmp/foo
$ echo 'bar' > /tmp/foo/bar
```

Output:
    added '/tmp/buz'
    modified '/tmp/buz'

Would be great to have some option like `:recursive => true` to watch `/tmp/foo/bar` in my example.

**Comment by NV** [comment]
`DirectoryWatcher.new '/tmp/**'` do the job. Silly me.

**Comment by TwP** [comment]
DirectoryWatcher.new '/tmp', :glob => '*_/_.txt'

That works also. You can give multiple glob patterns in order to select a specific subset of files to watch.

Blessings,
TwP
