### ISSUE TITLE
invalid date format in specification: "2011-08-30 00:00:00.000000000Z"

### ISSUE THREAD

**Issue by zandev** [TwP/directory_watcher#10]
Not sure if it's the right place, but, at the current date, when installing directory_watcher-1.4.1, there seem to have a problem in the gemspec file.

s.date = %q{2011-08-30 00:00:00.000000000Z}

Regarding the documentation here:

http://rubygems.rubyforge.org/rubygems-update/Gem/Specification.html#method-i-date

It seems that there is a problem. The date should be:

s.date = %q{2011-08-30}

**Comment by TwP** [comment]
The gemspec file is generated by RubyGems. It is not part of the project file. Any formatting discrepancies should be taken up with the RubyGems maintainers.

I can confirm that the date format is incorrect when using older versions of RubyGems -- version 1.3.7 shows this behavior. Using a more recent version of RubyGems -- version 1.8.6 has the correct date format.

**Comment by pepijndevos** [comment]
This is still an issue, as Debian users cannot easily upgrade RubyGems

**Comment by TwP** [comment]
The only solution for getting this error taken care of is to package them directory_watcher gem with the older version of rubygems installed on the target machine. The "bones" gem development tool is used internally by directory_watcher. 

Steps to install:

```
gem install bones
git clone https://github.com/TwP/directory_watcher.git
cd directory_watcher
rake gem
gem install pkg/directory_watcher-1.4.1.gem
```

Or you can distribute the directory_watcher gem file to other machines. You must ensure that the version of rubygems your are packaging with is the same as is installed on the machine where directory_watcher will be installed.
