### ISSUE TITLE
Ability to run as daemon

### ISSUE THREAD

**Issue by KevinInTx** [TwP/directory_watcher#11]
It would be nice to be able to run directory_watcher as a daemon behind the scenes.

**Comment by TwP** [comment]
Beyond the scope of this gem. Perhaps you would like to try [Serv-O-Lux](https://github.com/TwP/servolux) in conjunction with directory watcher!?

**Comment by TwP** [comment]
There is also [dirwatch](http://raa.ruby-lang.org/project/dirwatch/), [guard](https://github.com/guard/guard), and [watchr](https://github.com/mynyml/watchr). Any of those will do what you need - take a look at guard, though, as it is more widely used than the other two.

**Comment by KevinInTx** [comment]
Thanks for the info.
