### ISSUE TITLE
setting interval in the top level DW instances is not propagating to the inner classes

### ISSUE THREAD

**Issue by copiousfreetime** [TwP/directory_watcher#16]

**Comment by TwP** [comment]
Jeremy, here is a gist with my test scripts that are exhibiting the odd behaviors:

https://gist.github.com/1477410

**Comment by copiousfreetime** [comment]
This appears to be fixed, but I'm unsure what was done to fix it. I cannot duplicate it anymore. So long as dw.interval is set before dw.start is called, all is well.

**Comment by copiousfreetime** [comment]
Fixed with commit 58c0f490d1f8c90cc4f5d5e7f15f9f1752ed3625
