### ISSUE TITLE
new version of the gem?

### ISSUE THREAD

**Issue by bambery** [TwP/directory_watcher#20]
The gem and this repo both say 1.4.1, but the gem no longer reflects what are now old changes, ie breaking out event into a separate class, etc.

**Comment by parkr** [comment]
Yo @TwP! I'd love to use the latest stuff for @mojombo's Jekyll.

**Comment by parkr** [comment]
Also, I really like this gem. It is so awesome.

**Comment by TwP** [comment]
@parkr I'll put this on my list of open source things to get done this week. But I have my normal day job, my country's 500th anniversary to plan, my wife to murder, and Guilder to frame for it. I'm swamped!

**Comment by parkr** [comment]
@TwP Thanks for fitting this into your busy schedule :-)

**Comment by TwP** [comment]
Version 1.5.1 has been released.

**Comment by parkr** [comment]
bomb.  thanks man!
