### ISSUE TITLE
Neither Rev nor EM scanners work...

### ISSUE THREAD

**Issue by sdhull** [TwP/directory_watcher#3]
The Rev scanner simply never reports any events, while the EM scanner pukes with this error when I try to start it:

```
irb(main):006:0> dw.start
Errno::EINVAL: Invalid argument - must enable kqueue
  from /opt/local/ruby-enterprise-1.8.6-20090610/lib/ruby/gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:1266:in `watch_filename'
  from /opt/local/ruby-enterprise-1.8.6-20090610/lib/ruby/gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:1266:in `watch_file'
  from /opt/local/ruby-enterprise-1.8.6-20090610/lib/ruby/gems/1.8/gems/directory_watcher-1.4.0/lib/directory_watcher/em_scanner.rb:187:in `_watch_file'
  from /opt/local/ruby-enterprise-1.8.6-20090610/lib/ruby/gems/1.8/gems/directory_watcher-1.4.0/lib/directory_watcher/em_scanner.rb:69:in `start'
  from /opt/local/ruby-enterprise-1.8.6-20090610/lib/ruby/gems/1.8/gems/directory_watcher-1.4.0/lib/directory_watcher/em_scanner.rb:67:in `each'
  from /opt/local/ruby-enterprise-1.8.6-20090610/lib/ruby/gems/1.8/gems/directory_watcher-1.4.0/lib/directory_watcher/em_scanner.rb:67:in `start'
  from /opt/local/ruby-enterprise-1.8.6-20090610/lib/ruby/gems/1.8/gems/directory_watcher-1.4.0/lib/directory_watcher.rb:502:in `start'
  from (irb):6
```

**Comment by NV** [comment]
```
EM.kqueue = true
```

Rev scanner also works, but with about 2 seconds delay.

**Comment by sdhull** [comment]
Funny, I coulda sworn I tried that yesterday and it didn't work.  But now it does.  I must've done something different (ie, wrong) yesterday.

Aha!  If you try this:

```
dw = DirectoryWatcher.new '.', :glob => '**/*.txt', :pre_load => true, :scanner => :em
dw.add_observer {|*args| args.each {|event| puts event}}
dw.start
```

Get the error, then try

```
EM.kqueue  # no argument is needed
dw.start
```

That won't work.  Not sure why, though.  :-\
The weirdest part is that I recall being told by the EM developers that kqueue/epoll are turned on automatically on their respective platforms as of v0.12.0, I think.  In this case though, failing to call kqueue causes EM to irreparably break. After I get that error, even if I initialize a new DirectoryWatcher instance, it doesn't seem to matter:

```
require 'directory_watcher'
require 'eventmachine'
dw = DirectoryWatcher.new '.', :glob => '**/*.txt', :pre_load => true, :scanner => :em
dw.add_observer {|*args| args.each {|event| puts event}}
dw.start

dw = DirectoryWatcher.new '.', :glob => '**/*.txt', :pre_load => true, :scanner => :em
dw.add_observer {|*args| args.each {|event| puts event}}
EM.kqueue
dw.start
```

**Comment by TwP** [comment]
I'm calling this one closed. It would be great if EM figures out epoll or kqueue in the future. But for now, you do have to specify EM.kqueue _before_ starting a directory watcher instance.

Glad you got it all figured out. And thank you for documenting your findings here so others can find them.
