### ISSUE TITLE
Add gem dependency for "rev"

### ISSUE THREAD

**Issue by mkaito** [TwP/directory_watcher#5]
RevScanner relies on rev being installed, but this isn't mentioned anywhere, or at least I couldn't find a reference to it.

**Comment by TwP** [comment]
Hrmmm ... you are correct.

Rev has been superseded by cool.io (http://coolio.github.com). Perhaps it is time to move directory_watcher forward and use the newer goodness that Tony has thrown together.

Would you care to take a stab at this conversion to cool.io?

TwP

**Comment by TwP** [comment]
Documentation has been updated to note that the appropriate gem must be installed to use that scanner => cool.io / eventmachine / rev.
