### ISSUE TITLE
Monitor directory changes

### ISSUE THREAD

**Issue by masylum** [TwP/directory_watcher#6]
Hi, I'm using this gem to track directory changes and remap them on a mongo. It works perfectly on file changes but I can't get it working with folders.
I see on the scanner source that you skip folders from being scanned, why?
Could be an optional parameter to allow folder scanning?

https://github.com/TwP/directory_watcher/blob/master/lib/directory_watcher/scanner.rb#L119

Thanks!

**Comment by TwP** [comment]
I'm not exactly sure what constitutes a "changed" folder. The only piece of information to trigger on is the modification time. This changes if you touch the folder or if you change the contents of the folder, but that is about it.

Furthermore, several of the backends only report changes on files, not directories. Keeping things consistent across all backends is the biggest challenge here.

TwP

**Comment by masylum** [comment]
Renaming or touching a folder it doesn't trigger the observer.
Maybe I'm doing something wrong.

```
require 'directory_watcher'

puts File.expand_path('~/folder')
dw = DirectoryWatcher.new(File.expand_path('~/folder'), :glob => '**/*')
dw.interval = 5.0
dw.stable = 2
dw.add_observer {|*args| args.each {|event| puts event}}

dw.start
gets      # when the user hits "enter" the script will terminate
dw.stop
```

**Comment by TwP** [comment]
Correct. That is the expected behavior.

The backends file monitoring code used by directory watcher does not support monitoring of directories. For example, Rev (built on libev) does not allow directories to be monitored.

TwP

**Comment by masylum** [comment]
Ok, thanks for your fast answer! :)
